# Generated by Django 4.2.3 on 2023-08-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productinfo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.ForeignKey(blank=True, help_text='The Quality, Grade or Type of the Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productquality', verbose_name='Quality||Grade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize'),
        ),
    ]
