# Generated by Django 4.2.3 on 2023-08-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
        ('products', '0003_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categorys.productcategory'),
            preserve_default=False,
        ),
    ]
