# Generated by Django 4.2.3 on 2023-08-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_color_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productquality',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
    ]
