# Generated by Django 4.2.3 on 2023-08-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcolor_product_productquality_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.product'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='color', to='products.product'),
        ),
    ]
