# Generated by Django 4.2.3 on 2023-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productcolor_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquality',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.AddField(
            model_name='productquality',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='quality', to='products.product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='size', to='products.product'),
        ),
    ]
