# Generated by Django 4.2.3 on 2023-08-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productquality_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='productquality',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='product',
            new_name='products',
        ),
    ]
