# Generated by Django 4.2.3 on 2023-08-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_product_productcolor_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qunatity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
