# Generated by Django 4.2.3 on 2023-08-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_qunatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
