# Generated by Django 4.2.3 on 2023-09-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_vendor'),
        ('products', '0016_product_user_vendor_address_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorys.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
