# Generated by Django 4.2.3 on 2023-09-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_vendor_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
