# Generated by Django 4.2.3 on 2023-09-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customers_address'),
        ('products', '0020_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rating', to='users.customers'),
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='products',
        ),
        migrations.AddField(
            model_name='productrating',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='products.product'),
            preserve_default=False,
        ),
    ]
