# Generated by Django 4.2.3 on 2023-10-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products/images/<django.db.models.query_utils.DeferredAttribute object at 0x00000221EE34B6D0>/')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='products.product')),
            ],
        ),
    ]
