# Generated by Django 4.2.3 on 2023-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x00000169AC5BB310>/'),
        ),
    ]
