# Generated by Django 4.2.3 on 2023-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0006_address_directions_address_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
