# Generated by Django 4.2.3 on 2023-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
