# Generated by Django 4.2.3 on 2023-11-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pending_status',
            new_name='order_status',
        ),
    ]
