# Generated by Django 4.2.3 on 2023-12-19 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_address', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
