# Generated by Django 4.2.3 on 2023-10-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0003_customerprofile_remove_customers_address_and_more'),
        ('product', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rating', to='my_users.customerprofile'),
        ),
    ]
