# Generated by Django 4.2.3 on 2023-09-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address_customers_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='users.address'),
        ),
    ]
