# Generated by Django 4.2.3 on 2023-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0002_user_is_seller_alter_customers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
    ]
