# Generated by Django 4.2.3 on 2023-10-17 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer'),
        ('my_users', '0003_customerprofile_remove_customers_address_and_more'),
        ('product', '0003_alter_productrating_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_address', to='my_users.address'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
