# Generated by Django 4.2.3 on 2023-10-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0004_delete_customers_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user',
            new_name='account',
        ),
    ]
