# Generated by Django 4.2.3 on 2023-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0005_rename_user_customerprofile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='directions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
