# Generated by Django 4.2.3 on 2023-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0007_alter_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
