# Generated by Django 4.2.3 on 2023-11-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_myorderitems_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_order_items', to='order.myorder'),
        ),
    ]
