# Generated by Django 4.2.3 on 2023-11-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_myorderitems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorderitems',
            name='cartItems',
        ),
        migrations.RemoveField(
            model_name='myorderitems',
            name='product',
        ),
    ]
