# Generated by Django 4.2.3 on 2023-11-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_owner'),
        ('order', '0008_remove_myorderitems_cartitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorderitems',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_cart', to='cart.cart'),
        ),
    ]
