# Generated by Django 4.2.3 on 2023-11-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productrating_customer'),
        ('order', '0009_alter_myorderitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorderitems',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to='product.products'),
            preserve_default=False,
        ),
    ]
