# Generated by Django 4.2.3 on 2023-12-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_owner'),
        ('order', '0010_myorderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_order_cart', to='cart.cart'),
        ),
    ]
